-- ================================================
-- Seed Data: Consultation System
-- Description: Sample data for farms, consultants, and visits
-- Author: System
-- Created: 2026-01-18
-- ================================================

-- Insert sample consultants
INSERT INTO consultants (
    full_name, 
    email, 
    phone, 
    specialization, 
    experience_years, 
    certification, 
    bio, 
    service_areas, 
    availability_status, 
    rating, 
    total_consultations, 
    success_rate, 
    status
) VALUES 
(
    'Dr. Ahmad Suryadi',
    'ahmad.suryadi@petagri.com',
    '+62812345678',
    'Crop Management',
    15,
    ARRAY['Certified Agricultural Advisor', 'Integrated Pest Management Specialist'],
    'Experienced agricultural consultant with expertise in sustainable farming practices and crop optimization.',
    ARRAY['Jakarta', 'Bogor', 'Depok', 'Bekasi'],
    'available',
    4.8,
    156,
    92.5,
    'active'
),
(
    'Ir. Sari Indrawati',
    'sari.indrawati@petagri.com',
    '+62823456789',
    'Soil Health',
    12,
    ARRAY['Soil Science Certification', 'Organic Agriculture Specialist'],
    'Soil health expert specializing in soil fertility improvement and organic farming techniques.',
    ARRAY['Bandung', 'Tasikmalaya', 'Garut', 'Sumedang'],
    'available',
    4.9,
    134,
    94.2,
    'active'
),
(
    'Dr. Budi Santoso',
    'budi.santoso@petagri.com',
    '+62834567890',
    'Pest Control',
    10,
    ARRAY['IPM Certification', 'Biological Control Specialist'],
    'Pest management specialist with focus on environmentally friendly control methods.',
    ARRAY['Yogyakarta', 'Solo', 'Magelang', 'Klaten'],
    'busy',
    4.7,
    98,
    89.8,
    'active'
),
(
    'Ir. Maya Kusuma',
    'maya.kusuma@petagri.com',
    '+62845678901',
    'Hydroponic Systems',
    8,
    ARRAY['Hydroponic Certification', 'Greenhouse Management'],
    'Modern farming consultant specializing in hydroponic and controlled environment agriculture.',
    ARRAY['Surabaya', 'Malang', 'Kediri', 'Blitar'],
    'available',
    4.6,
    76,
    87.3,
    'active'
);

-- Insert sample farms
INSERT INTO farms (
    farm_name,
    owner_name,
    contact_email,
    contact_phone,
    address,
    province,
    city,
    total_area,
    crop_types,
    farming_method,
    established_year,
    current_season,
    irrigation_system,
    soil_type,
    climate_zone,
    farm_status,
    health_score
) VALUES
(
    'Kebun Sari Organik',
    'Pak Hendra Wijaya',
    'hendra.wijaya@gmail.com',
    '+62856789012',
    'Jl. Raya Pacet No. 123, Pacet, Cianjur',
    'Jawa Barat',
    'Cianjur',
    5.5,
    ARRAY['Rice', 'Vegetables', 'Herbs'],
    'organic',
    2018,
    'Dry Season 2026',
    'Drip irrigation',
    'Clay loam',
    'Tropical highland',
    'active',
    4.2
),
(
    'Agro Maju Sejahtera',
    'Ibu Retno Sari',
    'retno.sari@gmail.com',
    '+62867890123',
    'Desa Karanganyar, Kec. Ngawi, Ngawi',
    'Jawa Timur',
    'Ngawi',
    12.3,
    ARRAY['Corn', 'Cassava', 'Soybeans'],
    'conventional',
    2015,
    'Wet Season 2026',
    'Flood irrigation',
    'Alluvial',
    'Tropical lowland',
    'active',
    3.8
),
(
    'Green Valley Farm',
    'Pak Agus Priyono',
    'agus.priyono@gmail.com',
    '+62878901234',
    'Jl. Magelang Km 15, Sleman, Yogyakarta',
    'DIY',
    'Sleman',
    8.7,
    ARRAY['Lettuce', 'Tomatoes', 'Cucumbers'],
    'hydroponic',
    2020,
    'Year-round production',
    'Hydroponic NFT',
    'Controlled substrate',
    'Controlled environment',
    'active',
    4.5
),
(
    'Sawah Berkah',
    'Pak Made Sutrisno',
    'made.sutrisno@gmail.com',
    '+62889012345',
    'Br. Kedisan, Desa Kedisan, Kintamani',
    'Bali',
    'Bangli',
    3.2,
    ARRAY['Rice', 'Strawberries'],
    'conventional',
    2012,
    'Planting Season 2026',
    'Traditional subak',
    'Volcanic',
    'Highland tropical',
    'active',
    4.0
),
(
    'Urban Greens',
    'Ibu Linda Maharani',
    'linda.maharani@gmail.com',
    '+62890123456',
    'Jl. Kemang Raya No. 88, Kemang, Jakarta Selatan',
    'DKI Jakarta',
    'Jakarta Selatan',
    0.5,
    ARRAY['Microgreens', 'Herbs', 'Leafy vegetables'],
    'hydroponic',
    2022,
    'Continuous harvest',
    'Vertical hydroponic',
    'Rockwool substrate',
    'Controlled indoor',
    'active',
    4.1
);

-- Insert sample consultation visits
INSERT INTO consultation_visits (
    farm_id,
    consultant_id,
    scheduled_date,
    estimated_duration,
    visit_type,
    visit_status,
    actual_start_time,
    actual_end_time,
    consultation_notes,
    problems_identified,
    recommendations,
    recommended_products,
    visit_rating,
    farmer_feedback,
    consultant_feedback,
    follow_up_required,
    consultation_fee,
    travel_cost,
    payment_status
) VALUES 
(
    (SELECT id FROM farms WHERE farm_name = 'Kebun Sari Organik'),
    (SELECT id FROM consultants WHERE full_name = 'Dr. Ahmad Suryadi'),
    '2026-01-15 09:00:00+07',
    180,
    'initial',
    'completed',
    '2026-01-15 09:15:00+07',
    '2026-01-15 12:30:00+07',
    'Comprehensive initial assessment of organic farm. Good soil quality, excellent crop diversity. Some minor pest issues identified in vegetable section. Overall farm management is very good.',
    ARRAY['Minor aphid infestation in vegetable beds', 'Nitrogen deficiency in rice paddies', 'Irrigation timing needs optimization'],
    ARRAY['Introduce beneficial insects for aphid control', 'Apply organic nitrogen fertilizer', 'Adjust irrigation schedule to early morning', 'Implement companion planting'],
    ARRAY[], -- Will be populated with actual product IDs later
    4.5,
    'Very knowledgeable consultant. Gave practical solutions that we can implement immediately.',
    'Well-managed organic farm with motivated owner. Good potential for yield improvement with minor adjustments.',
    true,
    500000,
    75000,
    'paid'
),
(
    (SELECT id FROM farms WHERE farm_name = 'Agro Maju Sejahtera'),
    (SELECT id FROM consultants WHERE full_name = 'Ir. Sari Indrawati'),
    '2026-01-16 08:00:00+07',
    150,
    'regular',
    'completed',
    '2026-01-16 08:10:00+07',
    '2026-01-16 10:45:00+07',
    'Soil health assessment revealed good soil structure but low organic matter content. Corn yield has been declining over past 2 seasons. Recommended soil improvement strategies.',
    ARRAY['Low soil organic matter', 'Soil compaction in tractor pathways', 'Uneven nutrient distribution'],
    ARRAY['Add compost and organic matter', 'Implement controlled traffic farming', 'Conduct soil test mapping', 'Use variable rate fertilization'],
    ARRAY[],
    4.8,
    'Excellent soil analysis. Now we understand why our yields were declining. Thank you for the detailed recommendations.',
    'Farmer is very receptive to new techniques. Soil has good potential for improvement with proper management.',
    true,
    450000,
    50000,
    'paid'
),
(
    (SELECT id FROM farms WHERE farm_name = 'Green Valley Farm'),
    (SELECT id FROM consultants WHERE full_name = 'Ir. Maya Kusuma'),
    '2026-01-20 14:00:00+07',
    120,
    'regular',
    'scheduled',
    NULL,
    NULL,
    NULL,
    ARRAY[],
    ARRAY[],
    ARRAY[],
    NULL,
    NULL,
    NULL,
    false,
    400000,
    25000,
    'pending'
),
(
    (SELECT id FROM farms WHERE farm_name = 'Urban Greens'),
    (SELECT id FROM consultants WHERE full_name = 'Ir. Maya Kusuma'),
    '2026-01-22 10:00:00+07',
    90,
    'follow_up',
    'scheduled',
    NULL,
    NULL,
    NULL,
    ARRAY[],
    ARRAY[],
    ARRAY[],
    NULL,
    NULL,
    NULL,
    false,
    350000,
    35000,
    'pending'
),
(
    (SELECT id FROM farms WHERE farm_name = 'Sawah Berkah'),
    (SELECT id FROM consultants WHERE full_name = 'Dr. Budi Santoso'),
    '2026-01-18 13:00:00+07',
    135,
    'emergency',
    'in_progress',
    '2026-01-18 13:05:00+07',
    NULL,
    NULL,
    ARRAY[],
    ARRAY[],
    ARRAY[],
    NULL,
    NULL,
    NULL,
    false,
    600000,
    100000,
    'pending'
);